### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR

### ISSUE THREAD

**Issue by LeiHaoa** [bioinform/neusomatic#85]
Hi,
When I run NeuSomatic, I got the error:
```
Traceback (most recent call last):
  File "/home/user_home/haoz/vctools/neusomatic/neusomatic/python/call.py", line 610, in <module>
    raise e
  File "/home/user_home/haoz/vctools/neusomatic/neusomatic/python/call.py", line 605, in <module>
    use_cuda)
  File "/home/user_home/haoz/vctools/neusomatic/neusomatic/python/call.py", line 530, in call_neusomatic
    net, vartype_classes, call_loader, out_dir, model_tag, use_cuda)
  File "/home/user_home/haoz/vctools/neusomatic/neusomatic/python/call.py", line 77, in call_variants
    outputs, _ = net(matrices)
  File "/home/user_home/haoz/miniconda3/envs/neusomatic-gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user_home/haoz/miniconda3/envs/neusomatic-gpu/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/user_home/haoz/miniconda3/envs/neusomatic-gpu/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/user_home/haoz/miniconda3/envs/neusomatic-gpu/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/user_home/haoz/miniconda3/envs/neusomatic-gpu/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/user_home/haoz/miniconda3/envs/neusomatic-gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user_home/haoz/vctools/neusomatic/neusomatic/python/network.py", line 67, in forward
    x = self.pool1(F.relu(self.bn1(self.conv1(x))))
  File "/home/user_home/haoz/miniconda3/envs/neusomatic-gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user_home/haoz/miniconda3/envs/neusomatic-gpu/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR
```
I install NeuSomatic under the instruction in README.
 pytorch version: pytorch=1.1.0 torchvision=0.3.0 cudatoolkit=9.0 

do you have any suggestions?
                             Thanks!

**Comment by LeiHaoa** [comment]
The reason is that I use 3090, it needs cuda11
https://discuss.pytorch.org/t/cudnn-status-mapping-error-using-conv2d/136675
```
conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia
pip install --upgrade numpy
```
works for me
